#!/bin/bash

wid=$(xdotool search --classname urxvtq | head -1)
if [ -z "$wid" ]; then
  ''/usr/local/bin/urxvtc'' -pe tabbed -fn "xft:Blissymbolics-Courier:pixelsize=32" -sb -name urxvtq -geometry 80x28
  wid=$(xdotool search --classname urxvtq | head -1)
  xdotool windowfocus "$wid"
  xdotool key Control_L+l
else
  if [ -z "$(xdotool search --onlyvisible --classname urxvtq 2>/dev/null)" ]; then
    xdotool windowmap "$wid"
    xdotool windowfocus "$wid"
  else
    xdotool windowunmap "$wid"
  fi
fi

