#!/usr/bin/env python3
# Text to Unicode converter for putting Unicode text into locale files.
# Usage: ./encodestr <strtoconvert>
# e.g.: ./encodestr hello

import sys

def main():
    if len(sys.argv) != 2:
        exit(f'Usage: {sys.argv[0]} <string to encode>')
    print(encode(sys.argv[1]))

def encode(s):
    return ''.join(f"<U{ord(c):04X}>" for c in s)

if __name__ == '__main__':
    sys.exit(main())
